### ISSUE TITLE
Python 3

### ISSUE THREAD

**Issue by ocefpaf** [ioos/petulant-bear#8]
This package is at the bottom of a long dependency chain that prevent us from building Python 3.

**Comment by lukecampbell** [comment]
I'm trying to phase out petulant bear from... like everything.

**Comment by ocefpaf** [comment]
That works too :wink:

**Comment by lukecampbell** [comment]
It was a good idea but the project's purpose is deprecated by other projects that do similar functions and are less prone to unicode errors.

**Comment by ocefpaf** [comment]
Fixed in #9
